movies:
  outputs:
    docker:
      dataset: "{{ env_var('DBT_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: "{{ env_var('DBT_LOCATION') }}"
      method: oauth
      priority: interactive
      project: "{{ env_var('DBT_PROJECT') }}"
      threads: 5
      type: bigquery
  target: docker
